
###
POST http://localhost:8080/api/players?name=asdasdasd

###
GET http://localhost:8080/api/players

### Start game
POST http://localhost:8080/api/game/start

### Get game
GET http://localhost:8080/api/game

### Become host
POST http://localhost:8080/api/host?name=Максим

### Get game again
GET http://localhost:8080/api/game